remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: My Projects
description:
            Explore a curated collection of my coding projects, competition highlights, and notable achievements.<br><br><br>

            This page hosts projects featured in my CV, along with additional works. Certain CV projects are not included here due to course-related restrictions or confidentiality.