remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: My Projects
description: A showcase of my coding projects, competitions, and achievements.

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      stylesheets:
        - /assets/css/style.css